[theme]
primaryColor = "#087f8c"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#172b4d"
font = "sans serif"

[server]
maxUploadSize = 512

[browser]
gatherUsageStats = false
